tap_install:
  package_repository:
    oci_repository: e66b460d84234f8ab296fc5f9a973dff.azurecr.io/tap-green/tap-packages

namespace_provisioner:
  controller: false
  gitops_install:
    ref: origin/main
    subPath: clusters/user1/cluster-config/namespace-provisioner
    url: https://github.com/dbuchko/tap-gitops.git
