---
tap_install:
  values:
    shared:
      ingress_domain: "user1.tap-green.azure.tanzu-studio.com"

    ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

    #The above keys are minimum numbers of entries needed in tap-values.yaml to get a functioning TAP Full profile installation.

    #Below are the keys which may have default values set, but can be overridden.

    profile: full # Can take iterate, build, run, view.

    supply_chain: testing_scanning # Can take testing, testing_scanning.

    contour:
      envoy:
        service:
          type: LoadBalancer # This is set by default, but can be overridden by setting a different value.

    tap_gui:
      service_type: ClusterIP # If the shared.ingress_domain is set as earlier, this must be set to ClusterIP.
      metadataStoreAutoconfiguration: true # Create a service account, the Kubernetes control plane token and the requisite app_config block to enable communications between Tanzu Application Platform GUI and SCST - Store.
      app_config:
        catalog:
          locations:
            - type: url
              target: https://github.com/asaikali/tap-gui-sample-catalog/blob/main/catalog-info.yaml

    metadata_store:
      ns_for_export_app_cert: "dev"
      app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.

    scanning:
      metadataStore:
        url: "" # Configuration is moved, so set this string to empty.

    grype:
      namespace: "dev"
      targetImagePullSecret: registry-credentials

    namespace_provisioner:
      controller: false
      additional_sources:
      - git:
          ref: origin/main
          subPath: clusters/user1/cluster-config/namespace-provisioner/testing-supplychain
          url: https://github.com/dbuchko/tap-gitops.git
        path: _ytt_lib/testing-supplychain-setup
      - git:
          ref: origin/main
          subPath: clusters/user1/cluster-config/namespace-provisioner/testing-scanning-supplychain
          url: https://github.com/dbuchko/tap-gitops.git
        path: _ytt_lib/testing-scanning-supplychain-setup
      gitops_install:
        ref: origin/main
        subPath: clusters/user1/cluster-config/namespace-provisioner
        url: https://github.com/dbuchko/tap-gitops.git
