tap_install:
    sensitive_values:
        shared:
            image_registry:
                project_path: ENC[AES256_GCM,data:JqXHFa6FGoyH7INb8+lhPPWl6jjndResRJTe3KcwrsCxatdX8+kp7KZM9WDcbFbI9Xf2voiTStCLVxtGB/nI,iv:8U3SveBH0uVXd4dHhfEbDheBshWD/IhQYxDySBVIelc=,tag:0k5tIPzzgBUpCj1+8ow58g==,type:str]
                username: ENC[AES256_GCM,data:wEJ3nQq1IpnCbcjPO04Z0t97iJQoQQClu/GEjAOKyBo=,iv:loN4aGhmBr6RA1tOGNJyHzcgbTA+cBpr0JVRIrfSC68=,tag:r4f0UDW4aWEBD63evnIxtw==,type:str]
                password: ENC[AES256_GCM,data:65AswXu6W3K5ecn8r92CU6/yAA5Ij5tjdD25LvAU7//g4xSzjLHXSgVTN1b23HR+T2rh/w==,iv:kUs9ftRTS7oZPClutvzlvPVrkg2bVD0pjPtN9ql8y0E=,tag:0glalBYaIbsV//yXqsLDRg==,type:str]
        #ENC[AES256_GCM,data:UquFM4E2JefQTyCjxtO9CuJy0bT8Cms6aX7vpoAFcXgf1kckzwJfTWJvQcQEKZNIsmLoZEtVqbxpAdHfnQyKDqGEUISTSxnTwD003JldC2zss6J0B4Tfwc8YFRflwmSxFa3AMZwo7rQOiMsUftHaObHQ,iv:KAVE7WzMWb4BIAmSxsd8vZfFUtAyxFyzzoODD72wtDQ=,tag:kQlwwFJBW4zNgyuJ6PS9hw==,type:comment]
        ootb_supply_chain_testing:
            gitops:
                #ENC[AES256_GCM,data:vUXSbkdyKxRgfqbRhh4y60mZu+Ja5j1O/BJIDeN2FBMES3RBCbGt7r8Xe3QQsf8d4TkV+eyWg0U/D0f8AIzorexQN5yup3u7Lf7pj/lsizjBgw==,iv:sy4R2ASGeqO88VsJRy2nSLe3qqkvLp8rBBzwqWJmo/E=,tag:W9WrGq3QsBtBrxTboF2sEg==,type:comment]
                ssh_secret: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1njghc3x868qa7e69rhn3mq9sqw83wrh003kg4as4l3prvjz2vd8q2f0vcm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUV3YvOXduLzl5TWw2MzlK
            ODRZbVZZYWJiMWI3aVM1QjVKV3hPUjhzUmpJCkNOb1JCNC91WDgwYnB5UCsxbG9V
            dm5qdjd5Y0FUbnRKVjBtWHkvUWdQRVUKLS0tIDA0RmZSQ1ZSWlVISHJNWVZhSS9B
            S0J2Ujd3bGtFSzFtcWJCUUhhNjcyKzAKI8qt/uDshN5TSTICBLJ2lO2+jAFOrovy
            GpvOckTGXuoa6hng76yfv/3kMMT99VCS0585xw7bUDm438zG8nyYqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T21:36:04Z"
    mac: ENC[AES256_GCM,data:68VPe8uoCd6qhrPxs5uSEgT/tkdQ4KV4gs2AaJEwpqttFCDT1wVXnVNvJY0qLVQv0OKF/4tn9x72noIOkvABb/f1+gHQi185xUmFswnojVwQ2rYwECHwr6lDK2LizpEehxRn18JgltB6a6ewTsiQmJhCT4vOotNHChYdfwX9Qxs=,iv:d7dXo8RIVcdDITDHS82Em6EgiXQy+f3sU2IeYtYtLk8=,tag:YIIEE4HskM9v42q62Q0LWA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
